function data()
return {
	"Ahornweg",
	"Amselweg",
	"Am Sportplatz",
	"Bachstrasse",
	"Beethovenstrasse",
	"Bergstrasse",
	"Berliner Strasse",
	"Birkenstrasse",
	"Blumenstrasse",
	"Breslauer Strasse",
	"Brunnenstrasse",
	"Buchenweg",
	"Burgstrasse",
	"Danziger Strasse",
	"Dorfstrasse",
	"Drosselweg",
	"Erlenweg",
	"Fasanenweg",
	"Feldstrasse",
	"Finkenweg",
	"Fliederweg",
	"Friedhofstrasse",
	"Gartenstrasse",
	"Göthestrasse",
	"Grüner Weg",
	"Hauptstrasse",
	"Heideweg",
	"Im Winkel",
	"Industriestrasse",
	"Jahnstrasse",
	"Kapellenweg",
	"Kastanienweg",
	"Kiefernweg",
	"Kirchgasse",
	"Königsberger Strasse",
	"Lerchenweg",
	"Lessingstrasse",
	"Lindenstrasse",
	"Marktplatz",
	"Meisenweg",
	"Mittelstrasse",
	"Mozartstrasse",
	"Mühlenstrasse",
	"Mühlweg",
	"Neue Strasse",
	"Parkstrasse",
	"Poststrasse",
	"Raiffeisenstrasse",
	"Ringstrasse",
	"Römerstrasse",
	"Rosenweg",
	"Schillerstrasse",
	"Schlossstrasse",
	"Schulstrasse",
	"Schützenstrasse",
	"Talstrasse",
	"Tannenweg",
	"Tulpenweg",
	"Uhlandstrasse",
	"Waldstrasse",
	"Wichenweg",
	"Wiesenweg",
}
end
