function data()
return {
 "Adeje",
 "Albacete",
 "Alcalá de Guadaíra",
 "Alcalá de Henares",
 "Alcantarilla",
 "Alcira",
 "Alcobendas",
 "Alcorcón",
 "Alcoy",
 "Algeciras",
 "Alhaurín de la Torre",
 "Alicante",
 "Almería",
 "Andújar",
 "Antequera",
 "Aranjuez",
 "Arganda del Rey",
 "Arona",
 "Arrecife",
 "Arucas",
 "Ávila",
 "Avilés",
 "Badajoz",
 "Badalona",
 "Baracaldo",
 "Barcelona",
 "Basauri",
 "Benalmádena",
 "Benidorm",
 "Bilbao",
 "Blanes",
 "Boadilla del Monte",
 "Burgos",
 "Burjasot",
 "Cáceres",
 "Cádiz",
 "Cartagena",
 "Casteldefels",
 "Castellón de la Plana",
 "Cerdanyola del Vallès",
 "Chiclana de la Frontera",
 "Ciudad Real",
 "Collado Villalba",
 "Colmenar Viejo",
 "Córdoba",
 "Cornellà de Llobregat",
 "Coslada",
 "Cuenca",
 "Denia",
 "Don Benito",
 "Dos Hermanas",
 "Écija",
 "El Ejido",
 "El Prat de Llobregat",
 "El Puerto de S. M.",
 "Elche",
 "Elda",
 "Esplugues de Llobregat",
 "Estepona",
 "Ferrol",
 "Figueres",
 "Fuengirola",
 "Fuenlabrada",
 "Gandía",
 "Gavà",
 "Getafe",
 "Gijón",
 "Girona",
 "Granada",
 "Granadilla de Abona",
 "Granollers",
 "Guadalajara",
 "Guecho",
 "Hospitalet de Llobregat",
 "Huelva",
 "Huesca",
 "Igualada",
 "Irún",
 "Jaén",
 "Jerez de la Frontera",
 "La Coruña",
 "La Línea de la Concepción",
 "La Orotava",
 "La Rinconada",
 "Langreo",
 "Las Palmas de G. C.",
 "Las Rozas de Madrid",
 "Leganés",
 "León",
 "Linares",
 "Lleida",
 "Lloret de Mar",
 "Logroño",
 "Lorca",
 "Los Palacios y Villafranca",
 "Los Realejos",
 "Lucena",
 "Lugo",
 "Madrid",
 "Mairena del Aljarafe",
 "Majadahonda",
 "Málaga",
 "Manresa",
 "Marbella",
 "Mataró",
 "Mérida",
 "Mieres",
 "Mijas",
 "Miranda de Ebro",
 "Mislata",
 "Molina de Segura",
 "Mollet del Vallès",
 "Móstoles",
 "Motril",
 "Murcia",
 "Narón",
 "Onteniente",
 "Orense",
 "Orihuela",
 "Oviedo",
 "Palencia",
 "Pamplona",
 "Parla",
 "Paterna",
 "Pinto",
 "Plasencia",
 "Ponferrada",
 "Pontevedra",
 "Portugalete",
 "Pozuelo de Alarcón",
 "Puerto Real",
 "Puertollano",
 "Rentería",
 "Reus",
 "Rincón de la Victoria",
 "Ripollet",
 "Rivas-Vaciamadrid",
 "Ronda",
 "Roquetas de Mar",
 "Rubí",
 "S. Bartolomé de T.",
 "Sabadell",
 "Sagunto",
 "Salamanca",
 "San Cristóbal de la Laguna",
 "San Fernando",
 "San Fernando de Henares",
 "San Sebastián",
 "San Sebastián de los Reyes",
 "San Vicente del Raspeig",
 "Sanlúcar de Barrameda",
 "Sant Boi de Llobregat",
 "Sant Cugat del Vallès",
 "Sant Feliu de Llobregat",
 "Santa Coloma de Gramanet",
 "Santa Cruz de Tenerife",
 "Santa Lucía de Tirajana",
 "Santander",
 "Santiago de Compostela",
 "Santurce",
 "Segovia",
 "Sevilla",
 "Siero",
 "Sitges",
 "Soria",
 "Talavera de la Reina",
 "Tarragona",
 "Tarrasa",
 "Telde",
 "Toledo",
 "Tomelloso",
 "Torrejón de Ardoz",
 "Torrelavega",
 "Torremolinos",
 "Torrente",
 "Torrevieja",
 "Tres Cantos",
 "Úbeda",
 "Utrera",
 "Valdemoro",
 "Valencia",
 "Valladolid",
 "Vélez-Málaga",
 "Vendrell",
 "Vic",
 "Vigo",
 "Viladecans",
 "Vilafranca del Penedés",
 "Vilanova i la Geltrú",
 "Villagarcía de Arosa",
 "Villarreal",
 "Vitoria",
 "Zamora",
 "Zaragoza",
}
end
