function data()
return {
	"Allée des Hortensias",
	"Allée des Bouleaux",
	"Allée des Erables",
	"Avenue de l'Observatoire",
	"Avenue E.Herriot",
	"Avenue Montaigne",
	"Avenue Mozart",
	"Boulevard Beaumarchais",
	"Boulevard Blanqui",
	"Boulevard St-Germain",
	"Cours Jean-Jaurès",
	"Cours Mirabeau",
	"Grande Rue",
	"Impasse Budgétaire",
	"Pont des Arts",
	"Pont Neuf",
	"Pont Royal",
	"Rue Aimé Cézaire",
	"Rue Albert-Camus",
	"Rue Albert Einstein",
	"Rue Albert Londres",
	"Rue Alexandre Dumas",
	"Rue Alfred de Musset",
	"Rue Alfred de Vigny",
	"Rue Alphonse Daudet",
	"Rue Ambroise-Croizat",
	"Rue Ampère",
	"Rue Anatole France",
	"Rue André Gide",
	"Rue Anne Frank",
	"Rue Aristide-Briand",
	"Rue Auguste Comte",
	"Rue Auguste Rodin",
	"Rue Balzac",
	"Rue Bartholdi",
	"Rue Basse",
	"Rue Beaumarchais",
	"Rue Berthelot",
	"Rue Bernard Clavel",
	"Rue Boris-Vian",
	"Rue Bossuet",
	"Rue Buffon",
	"Rue Camille Claudel",
	"Rue Camille-Flammarion",
	"Rue Camille Saint-Saëns",
	"Rue Cassini",
	"Rue Champollion",
	"Rue Charles Baudelaire",
	"Rue Charles Gounod",
	"Rue Charles Nodier",
	"Rue Charles Perrault",
	"Rue Claude Debussy",
	"Rue Claude Monet",
	"Rue Condorcet",
	"Rue Copernic",
	"Rue Courbet",
	"Rue d'Alésia",
	"Rue d'Alsace",
	"Rue d'Arbois",
	"Rue Darius Milhaud",
	"Rue Daumier",
	"Rue de Beaune",
	"Rue de Bourgogne",
	"Rue de Chambertin",
	"Rue de Champagne",
	"Rue de Genève",
	"Rue de l'Abbaye",
	"Rue de l'Egalité",
	"Rue de l'Eglise",
	"Rue de l'Ermitage",
	"Rue de l'Etoile",	
	"Rue de l'Hôpital",
	"Rue de la Chapelle",
	"Rue de la Citadelle",
	"Rue de la Collégiale",
	"Rue de la Comédie",
	"Rue de la Convention",
	"Rue de la Ferronnerie",
	"Rue de la Fontaine",
	"Rue de la Gare",
	"Rue de la Harpe",
	"Rue de la Liberté",
	"Rue de la Monnaie",
	"Rue de la Paix",
	"Rue de la République",
	"Rue de la Sablière",
	"Rue de la Source",
	"Rue de la Victoire",
	"Rue de l'Evêché",
	"Rue de l'Horloge",
	"Rue de Lille",
	"Rue de Lyon",
	"Rue de Rivoli",
	"Rue de Savoie",
	"Rue de Strasbourg",
	"Rue de Verdun",
	"Rue des Alouettes",
	"Rue des Alpes",
	"Rue des Arènes",
	"Rue des Augustins",
	"Rue des Boucheries",
	"Rue des Capucins",
	"Rue des Dames",
	"Rue des Daphnés",
	"Rue des Ecoles",
	"Rue des Fossés",
	"Rue des Fougères",
	"Rue des Frères Lumière",
	"Rue des Grands Moulins",
	"Rue des Glycines",
	"Rue des Jardins",
	"Rue des Lilas",
	"Rue des Maraîchers",
	"Rue des Moines",
	"Rue des Myosotis",
	"Rue des Oiseaux",
	"Rue des Orchidées",
	"Rue des Orfèvres",
	"Rue des Pêcheurs",
	"Rue des Peupliers",
	"Rue des Poissonniers",
	"Rue des Pyrénées",
	"Rue des Roses",
	"Rue des Rosiers",
	"Rue des Tilleuls",
	"Rue Descartes",
	"Rue Diderot",
	"Rue du Beaujolais",
	"Rue du Calvaire",
	"Rue du Champ de Foire ",
	"Rue du Charolais",
	"Rue du Château",
	"Rue du Château d'Eau",
	"Rue du Commerce",
	"Rue du Four",
	"Rue du Jura",
	"Rue du Lavoir",
	"Rue du Maine",
	"Rue du Marché",
	"Rue du Midi",
	"Rue du Moulin",
	"Rue du Paradis",	
	"Rue du Parc",
	"Rue du Spoutnik",
	"Rue du Stade",
	"Rue du Temple",
	"Rue du Théâtre",
	"Rue Duke Ellington",
	"Rue Edgar Degas",
	"Rue Edouard Manet",
	"Rue Emile Zola",
	"Rue Erik Satie",
	"Rue Eugène Delacroix",
	"Rue Faidherbe",
	"Rue Faraday",
	"Rue Fénelon",
	"Rue Francis Poulenc",
	"Rue François 1er",
	"Rue François Couperin",
	"Rue François Villon",
	"Rue Frédéric-Mistral",
	"Rue Fresnel",
	"Rue Gabriel Fauré",
	"Rue Galilée",
	"Rue Garibaldy",
	"Rue Georges Bizet",
	"Rue Georges Feydeau",
	"Rue George-Sand",
	"Rue Gérard de Nerval",
	"Rue Gérard Philipe",
	"Rue Goethe",
	"Rue Gustave Charpentier",
	"Rue Gustave Courbet",
	"Rue Gustave Eiffel",
	"Rue Gustave Flaubert",
	"Rue Gutenberg",
	"Rue Haute",
	"Rue Hector Berlioz",
	"Rue Huygens",
	"Rue J-Jacques Rousseau",
	"Rue Jacques Callot",
	"Rue Jacques Cœur",
	"Rue Jacques Prévert",
	"Rue Jean Bart",
	"Rue Jean Cocteau",
	"Rue Jean de la Fontaine",
	"Rue Jean Giono",
	"Rue Jean Giraudoux",
	"Rue Jean Jaurès",
	"Rue Jean Mermoz",
	"Rue Jeanne d'Arc",
	"Rue Joliot-Curie",
	"Rue Jules Ferry",
	"Rue Jules Guesde",
	"Rue Jules Vallès",
	"Rue Jules Verne",
	"Rue Képler",
	"Rue L.de Vinci",
	"Rue Lamartine",
	"Rue Lavoisier",
	"Rue Lecourbe",
	"Rue Leibniz",
	"Rue Léon Blum",
	"Rue Linné",
	"Rue Louis Aragon",
	"Rue Louis Armstrong",
	"Rue Lulli",
	"Rue Marcel Aymé",
	"Rue Marcel Pagnol",
	"Rue Marcel Proust",
	"Rue Maupassant",
	"Rue Maurice Ravel",
	"Rue Michel-Ange",
	"Rue Miles Davis",
	"Rue Mirabeau",
	"Rue Molière",
	"Rue Monge",
	"Rue Niepce",
	"Rue Parmentier",
	"Rue Pascal",
	"Rue Pasteur",
	"Rue Paul Cézanne",
	"Rue Paul Claudel",
	"Rue Paul Eluard",
	"Rue Paul Fort",
	"Rue Paul Gauguin",
	"Rue Paul Valéry",
	"Rue Paul Verlaine",
	"Rue Picasso",
	"Rue Pierre Corneille",
	"Rue Pierre et Marie Curie",
	"Rue Proudhon",
	"Rue Ptolémée",
	"Rue Racine",
	"Rue Rembrandt",
	"Rue Renan",
	"Rue Renoir",
	"Rue Robert Doisneau",
	"Rue Romain Rolland",
	"Rue Ronsard",
	"Rue Rouget-de-l'Isle",
	"Rue Sandro Botticelli",
	"Rue Sidney Bechet",
	"Rue Stendhal",
	"Rue Victor Hugo",
	"Rue Vincent Van Gogh",
	"Rue Violet",
	"Rue Volta",
	"Rue Voltaire",
}
end
