function data()
return {
	"Avenue de l'Observatoire",
	"Avenue E.Herriot",
	"Avenue Montaigne",
	"Boulevard Beaumarchais",
	"Boulevard Blanqui",
	"Cours Jean-Jaurès",
	"Cours Mirabeau",
	"Impasse Budgétaire",
	"Rue Aimé Cézaire",
	"Rue Albert Einstein",
	"Rue Albert Londres",
	"Rue Alexandre Dumas",
	"Rue Alfred de Musset",
	"Rue Alfred de Vigny",
	"Rue Alphonse Daudet",
	"Rue Ambroise-Croizat",
	"Rue Ampère",
	"Rue Anatole France",
	"Rue André Gide",
	"Rue Anne Frank",
	"Rue Auguste Comte",
	"Rue Auguste Rodin",
	"Rue Balzac",
	"Rue Bartholdi",
	"Rue Buffon",
	"Rue Camille Claudel",
	"Rue Camille Saint-Saëns",
	"Rue Charles Baudelaire",
	"Rue Charles Gounod",
	"Rue Charles Nodier",
	"Rue Charles Perrault",
	"Rue Claude Debussy",
	"Rue Claude Monet",
	"Rue Condorcet",
	"Rue Copernic",
	"Rue Courbet",
	"Rue d'Alsace",
	"Rue Darius Milhaud",
	"Rue de Genève",
	"Rue de l'Egalité",
	"Rue de l'Eglise",
	"Rue de l'Ermitage",	
	"Rue de l'Hôpital",
	"Rue de la Chapelle",
	"Rue de la Convention",
	"Rue de la Liberté",
	"Rue de la République",
	"Rue de la Victoire",
	"Rue de Verdun",
	"Rue des Augustins",
	"Rue des Capucins",
	"Rue des Daphnés",
	"Rue des Ecoles",
	"Rue des Fossés",
	"Rue des Fougères",
	"Rue des Frères Lumière",
	"Rue des Jardins",
	"Rue des Lilas",
	"Rue des Maraîchers",
	"Rue des Myosotis",
	"Rue des Roses",
	"Rue Descartes",
	"Rue Diderot",
	"Rue du Champ de Foire ",
	"Rue du Commerce",
	"Rue du Jura",
	"Rue du Moulin",
	"Rue du Parc",
	"Rue du Théâtre",
	"Rue Duke Ellington",
	"Rue Edgar Degas",
	"Rue Edouard Manet",
	"Rue Emile Zola",
	"Rue Erik Satie",
	"Rue Eugène Delacroix",
	"Rue Francis Poulenc",
	"Rue François 1er",
	"Rue François Couperin",
	"Rue François Villon",
	"Rue Gabriel Fauré",
	"Rue Georges Bizet",
	"Rue Georges Feydeau",
	"Rue Gérard de Nerval",
	"Rue Gérard Philipe",
	"Rue Gustave Charpentier",
	"Rue Gustave Courbet",
	"Rue Gustave Eiffel",
	"Rue Gustave Flaubert",
	"Rue Gutenberg",
	"Rue Hector Berlioz",
	"Rue J-Jacques Rousseau",
	"Rue Jacques Callot",
	"Rue Jacques Cœur",
	"Rue Jacques Prévert",
	"Rue Jean Bart",
	"Rue Jean Cocteau",
	"Rue Jean de la Fontaine",
	"Rue Jean Giono",
	"Rue Jean Giraudoux",
	"Rue Jean Jaurès",
	"Rue Jean Mermoz",
	"Rue Jeanne d'Arc",
	"Rue Joliot-Curie",
	"Rue Jules Ferry",
	"Rue Jules Guesde",
	"Rue Jules Vallès",
	"Rue Jules Verne",
	"Rue L.de Vinci",
	"Rue Lamartine",
	"Rue Lavoisier",
	"Rue Lecourbe",
	"Rue Léon Blum",
	"Rue Louis Aragon",
	"Rue Louis Armstrong",
	"Rue Lulli",
	"Rue Marcel Aymé",
	"Rue Marcel Pagnol",
	"Rue Marcel Proust",
	"Rue Maupassant",
	"Rue Maurice Ravel",
	"Rue Michel Ange",
	"Rue Miles Davis",
	"Rue Mirabeau",
	"Rue Molière",
	"Rue Parmentier",
	"Rue Pascal",
	"Rue Pasteur",
	"Rue Paul Cézanne",
	"Rue Paul Claudel",
	"Rue Paul Fort",
	"Rue Paul Gauguin",
	"Rue Paul Valéry",
	"Rue Paul Verlaine",
	"Rue Picasso",
	"Rue Pierre Corneille",
	"Rue Pierre et Marie Curie",
	"Rue Proudhon",
	"Rue Ptolémée",
	"Rue Racine",
	"Rue Rembrandt",
	"Rue Renan",
	"Rue Renoir",
	"Rue Robert Doisneau",
	"Rue Romain Rolland",
	"Rue Ronsard",
	"Rue Sandro Botticelli",
	"Rue Sidney Bechet",
	"Rue Stendhal",
	"Rue Victor Hugo",
	"Rue Vincent Van Gogh",
	"Rue Violet",
	"Rue Volta",
	"Rue Voltaire",
}
end
