function data()
return {
	"Calle del Abeto", 
	"Calle Acacia",
	"Calle Adelfa", 
	"Calle de la Alameda", 
	"Calle del Álamo", 
	"Calle de Albacete", 
	"Calle Alcalde Andrés Alarcón Soler", 
	"Calle Alcorcón", 
	"Calle Aldea del Fresno", 
	"Calle Alhelí", 
	"Calle Aliatar",
	"Calle de Alicante", 
	"Calle de Almería", 
	"Calle de Cerro Pinitos", 
	"Calle Ciempozuelos", 
	"Calle Ciudad Real", 
	"Calle Clavel", 
	"Calle Cobre", 
	"Avenida Comunidad de Madrid", 
	"Calle Concejo", 
	"Calle del Conde", 
	"Calle Plaza de la Constitución", 
	"Calle de Córdoba", 
	"Calle Cubas", 
	"Camino de Cubas", 
	"Calle del Escorial", 
	"Avenida de España", 
	"Avenida Estación", 
	"Calle de la Estación", 
	"Calle de Estanislao Zazo", 
	"Calle de la Estrella", 
	"Calle del Hierro", 
	"Calle la Higuera", 
	"Calle de Huelva", 
	"Calle las Huertas", 
	"Calle de Jacinto Benavente", 
	"Calle Jacintos", 
	"Calle de Jaén", 
	"Calle del Jardín",
	"Calle Leganés", 
	"Calle de la Libertad", 
	"Calle Libro", 
	"Calle de Logroño", 
	"Calle de la Luz", 
	"Calle de Ordesa", 
	"Calle Orestes", 
	"Calle de la Orquídea", 
	"Calle Osiris", 
	"Calle Oviedo",
	"Calle del Río Manzanares", 
	"Calle Roble", 
	"Calle de Rocinante", 
	"Calle Roma", 
	"Calle de Roquenublo", 
	"Calle Rosal", 
	"Calle de Tokio", 
	"Camino de Toledo", 
	"Camino de Torrejón", 
	"Calle Torrejón de la Calzada", 
	"Calle Tulipán", 
	"Camino Vereda de la Cruz", 
	"Camino Vereda del Lomo", 
	"Camino de la Vía", 
	"Calle de Vicente Aleixandre", 
	"Villaviciosa de Odón", 
	"Calle de las Viñas", 
	"Calle Violeta", 
}
end




