function data()
return {
	"Aach",
	"Aachen",
	"Aalen",
	"Abenberg",
	"Abensberg",
	"Achern",
	"Achim",
	"Adelsheim",
	"Adenau",
	"Adorf",
	"Ahaus",
	"Ahlen",
	"Ahrensburg",
	"Aichach",
	"Aichtal",
	"Aken",
	"Albstadt",
	"Alfeld",
	"Allendorf",
	"Allstedt",
	"Alpirsbach",
	"Alsdorf",
	"Alsfeld",
	"Alsleben",
	"Altdorf bei Nürnberg",
	"Altena",
	"Altenberg",
	"Altenburg",
	"Altenkirchen",
	"Altensteig",
	"Altentreptow",
	"Altlandsberg",
	"Altötting",
	"Alzenau",
	"Alzey",
	"Amberg",
	"Amöneburg",
	"Amorbach",
	"Andernach",
	"Angermünde",
	"Anklam",
	"Annaberg-Buchholz",
	"Annaburg",
	"Annweiler am Trifels",
	"Ansbach",
	"Apolda",
	"Arendsee",
	"Arneburg",
	"Arnis",
	"Arnsberg",
	"Arnstadt",
	"Arnstein",
	"Artern/Unstrut",
	"Arzberg",
	"Aschaffenburg",
	"Aschersleben",
	"Asperg",
	"Asslar",
	"Attendorn",
	"Aub",
	"Aue",
	"Auerbach",
	"Auerbach in der Oberpfalz",
	"Augsburg",
	"Augustusburg",
	"Aulendorf",
	"Auma-Weidatal",
	"Aurich",
	"Babenhausen",
	"Bacharach",
	"Backnang",
	"Bad Aibling",
	"Bad Arolsen",
	"Bad Belzig",
	"Bad Bentheim",
	"Bad Bergzabern",
	"Bad Berka",
	"Bad Berleburg",
	"Bad Berneck im Fichtelgebirge",
	"Bad Bevensen",
	"Bad Bibra",
	"Bad Blankenburg",
	"Bad Bramstedt",
	"Bad Breisig",
	"Bad Brückenau",
	"Bad Buchau",
	"Bad Camberg",
	"Bad Colberg-Heldburg",
	"Bad Doberan",
	"Bad Driburg",
	"Bad Düben",
	"Bad Dürkheim",
	"Bad Dürrenberg",
	"Bad Dürrheim",
	"Bad Elster",
	"Bad Ems",
	"Baden-Baden",
	"Bad Fallingbostel",
	"Bad Frankenhausen/Kyffhäuser",
	"Bad Freienwalde",
	"Bad Friedrichshall",
	"Bad Gandersheim",
	"Bad Gottleuba-Berggiesshübel",
	"Bad Griesbach im Rottal",
	"Bad Harzburg",
	"Bad Herrenalb",
	"Bad Hersfeld",
	"Bad Homburg vor der Höhe",
	"Bad Honnef",
	"Bad Hönningen",
	"Bad Iburg",
	"Bad Karlshafen",
	"Bad Kissingen",
	"Bad König",
	"Bad Königshofen im Grabfeld",
	"Bad Köstritz",
	"Bad Kötzting",
	"Bad Kreuznach",
	"Bad Krozingen",
	"Bad Laasphe",
	"Bad Langensalza",
	"Bad Lauchstädt",
	"Bad Lausick",
	"Bad Lauterberg im Harz",
	"Bad Liebenstein",
	"Bad Liebenwerda",
	"Bad Liebenzell",
	"Bad Lippspringe",
	"Bad Lobenstein",
	"Bad Marienberg",
	"Bad Mergentheim",
	"Bad Münder am Deister",
	"Bad Münstereifel",
	"Bad Muskau",
	"Bad Nauheim",
	"Bad Nenndorf",
	"Bad Neuenahr-Ahrweiler",
	"Bad Neustadt an der Saale",
	"Bad Oeynhausen",
	"Bad Oldesloe",
	"Bad Orb",
	"Bad Pyrmont",
	"Bad Rappenau",
	"Bad Reichenhall",
	"Bad Rodach",
	"Bad Sachsa",
	"Bad Säckingen",
	"Bad Salzdetfurth",
	"Bad Salzuflen",
	"Bad Salzungen",
	"Bad Saulgau",
	"Bad Schandau",
	"Bad Schmiedeberg",
	"Bad Schussenried",
	"Bad Schwalbach",
	"Bad Schwartau",
	"Bad Segeberg",
	"Bad Sobernheim",
	"Bad Soden am Taunus",
	"Bad Soden-Salmünster",
	"Bad Sooden-Allendorf",
	"Bad Staffelstein",
	"Bad Sulza",
	"Bad Sülze",
	"Bad Teinach-Zavelstein",
	"Bad Tennstedt",
	"Bad Tölz",
	"Bad Urach",
	"Bad Vilbel",
	"Bad Waldsee",
	"Bad Wildbad",
	"Bad Wildungen",
	"Bad Wilsnack",
	"Bad Wimpfen",
	"Bad Windsheim",
	"Bad Wörishofen",
	"Bad Wünnenberg",
	"Bad Wurzach",
	"Baesweiler",
	"Baiersdorf",
	"Balingen",
	"Ballenstedt",
	"Balve",
	"Bamberg",
	"Barby",
	"Bargteheide",
	"Barmstedt",
	"Bärnau",
	"Barntrup",
	"Barsinghausen",
	"Barth",
	"Baruth/Mark",
	"Bassum",
	"Battenberg",
	"Baumholder",
	"Baunach",
	"Baunatal",
	"Bautzen",
	"Bayreuth",
	"Bebra",
	"Beckum",
	"Bedburg",
	"Beelitz",
	"Beerfelden",
	"Beeskow",
	"Beilngries",
	"Beilstein",
	"Belgern-Schildau",
	"Bendorf",
	"Bensheim",
	"Berching",
	"Berga/Elster",
	"Bergen",
	"Bergen auf Rügen",
	"Bergheim",
	"Bergisch Gladbach",
	"Bergkamen",
	"Bergneustadt",
	"Berka/Werra",
	"Berlin",
	"Bernau bei Berlin",
	"Bernburg",
	"Bernkastel-Kues",
	"Bernsdorf",
	"Bernstadt a. d. Eigen",
	"Bersenbrück",
	"Besigheim",
	"Betzdorf",
	"Betzenstein",
	"Beverungen",
	"Bexbach",
	"Biberach an der Riss",
	"Biedenkopf",
	"Bielefeld",
	"Biesenthal",
	"Bietigheim-Bissingen",
	"Billerbeck",
	"Bingen am Rhein",
	"Birkenfeld",
	"Bischofsheim an der Rhön",
	"Bischofswerda",
	"Bismark",
	"Bitburg",
	"Bitterfeld-Wolfen",
	"Blankenburg",
	"Blankenhain",
	"Blaubeuren",
	"Blaustein",
	"Bleckede",
	"Bleicherode",
	"Blieskastel",
	"Blomberg",
	"Blumberg",
	"Bobingen",
	"Böblingen",
	"Bocholt",
	"Bochum",
	"Bockenem",
	"Bodenwerder",
	"Bogen",
	"Böhlen",
	"Boizenburg/Elbe",
	"Bonn",
	"Bonndorf im Schwarzwald",
	"Bönnigheim",
	"Bopfingen",
	"Boppard",
	"Borgentreich",
	"Borgholzhausen",
	"Borken",
	"Borkum",
	"Borna",
	"Bornheim",
	"Bottrop",
	"Boxberg",
	"Brackenheim",
	"Brake",
	"Brakel",
	"Bramsche",
	"Brandenburg an der Havel",
	"Brand-Erbisdorf",
	"Brandis",
	"Braubach",
	"Braunfels",
	"Braunlage",
	"Bräunlingen",
	"Braunsbedra",
	"Braunschweig",
	"Breckerfeld",
	"Bredstedt",
	"Breisach",
	"Bremen",
	"Bremerhaven",
	"Bremervörde",
	"Bretten",
	"Breuberg",
	"Brilon",
	"Brotterode-Trusetal",
	"Bruchköbel",
	"Bruchsal",
	"Brück",
	"Brüel",
	"Brühl",
	"Brunsbüttel",
	"Brüssow",
	"Buchen",
	"Buchholz in der Nordheide",
	"Buchloe",
	"Bückeburg",
	"Buckow",
	"Büdelsdorf",
	"Büdingen",
	"Bühl",
	"Bünde",
	"Büren",
	"Burg",
	"Burgau",
	"Burgbernheim",
	"Burgdorf",
	"Bürgel",
	"Burghausen",
	"Burgkunstadt",
	"Burglengenfeld",
	"Burgstädt",
	"Burg Stargard",
	"Burgwedel",
	"Burladingen",
	"Burscheid",
	"Bürstadt",
	"Buttelstedt",
	"Buttstädt",
	"Butzbach",
	"Bützow",
	"Buxtehude",
	"Calau",
	"Calbe",
	"Calw",
	"Castrop-Rauxel",
	"Celle",
	"Cham",
	"Chemnitz",
	"Clausthal-Zellerfeld",
	"Clingen",
	"Cloppenburg",
	"Coburg",
	"Cochem",
	"Coesfeld",
	"Colditz",
	"Cologne",
	"Coswig",
	"Cottbus",
	"Crailsheim",
	"Creglingen",
	"Creussen",
	"Creuzburg",
	"Crimmitschau",
	"Crivitz",
	"Cuxhaven",
	"Dachau",
	"Dahlen",
	"Dahme/Mark",
	"Dahn",
	"Damme",
	"Dannenberg",
	"Dargun",
	"Darmstadt",
	"Dassel",
	"Dassow",
	"Datteln",
	"Daun",
	"Deggendorf",
	"Deidesheim",
	"Delbrück",
	"Delitzsch",
	"Delmenhorst",
	"Demmin",
	"Dessau-Rosslau",
	"Detmold",
	"Dettelbach",
	"Dieburg",
	"Diemelstadt",
	"Diepholz",
	"Dierdorf",
	"Dietenheim",
	"Dietfurt an der Altmühl",
	"Dietzenbach",
	"Diez",
	"Dillenburg",
	"Dillingen an der Donau",
	"Dillingen/Saar",
	"Dingelstädt",
	"Dingolfing",
	"Dinkelsbühl",
	"Dinklage",
	"Dinslaken",
	"Dippoldiswalde",
	"Dissen am Teutoburger Wald",
	"Ditzingen",
	"Döbeln",
	"Doberlug-Kirchhain",
	"Döbern",
	"Dohna",
	"Dömitz",
	"Dommitzsch",
	"Donaueschingen",
	"Donauwörth",
	"Donzdorf",
	"Dorfen",
	"Dormagen",
	"Dornburg-Camburg",
	"Dornhan",
	"Dornstetten",
	"Dorsten",
	"Dortmund",
	"Dransfeld",
	"Drebkau",
	"Dreieich",
	"Drensteinfurt",
	"Dresden",
	"Drolshagen",
	"Duderstadt",
	"Duisburg",
	"Dülmen",
	"Düren",
	"Düsseldorf",
	"Ebeleben",
	"Eberbach",
	"Ebermannstadt",
	"Ebern",
	"Ebersbach an der Fils",
	"Ebersbach-Neugersdorf",
	"Ebersberg",
	"Eberswalde",
	"Eckartsberga",
	"Eckernförde",
	"Edenkoben",
	"Egeln",
	"Eggenfelden",
	"Eggesin",
	"Ehingen",
	"Ehrenfriedersdorf",
	"Eibelstadt",
	"Eibenstock",
	"Eichstätt",
	"Eilenburg",
	"Einbeck",
	"Eisenach",
	"Eisenberg",
	"Eisenhüttenstadt",
	"Eisfeld",
	"Eisleben",
	"Eislingen/Fils",
	"Ellingen",
	"Ellrich",
	"Ellwangen",
	"Elmshorn",
	"Elsdorf",
	"Elsfleth",
	"Elsterberg",
	"Elsterwerda",
	"Elstra",
	"Elterlein",
	"Eltmann",
	"Eltville am Rhein",
	"Elzach",
	"Elze",
	"Emden",
	"Emmelshausen",
	"Emmendingen",
	"Emmerich am Rhein",
	"Emsdetten",
	"Endingen",
	"Engen",
	"Enger",
	"Ennepetal",
	"Ennigerloh",
	"Eppelheim",
	"Eppingen",
	"Eppstein",
	"Erbach",
	"Erbendorf",
	"Erding",
	"Erftstadt",
	"Erfurt",
	"Erkelenz",
	"Erkner",
	"Erkrath",
	"Erlangen",
	"Erlenbach am Main",
	"Erlensee",
	"Erwitte",
	"Eschborn",
	"Eschenbach in der Oberpfalz",
	"Eschershausen",
	"Eschwege",
	"Eschweiler",
	"Esens",
	"Espelkamp",
	"Essen",
	"Esslingen am Neckar",
	"Ettenheim",
	"Ettlingen",
	"Euskirchen",
	"Eutin",
	"Falkenberg/Elster",
	"Falkensee",
	"Falkenstein/Harz",
	"Falkenstein/Vogtl.",
	"Fehmarn",
	"Fellbach",
	"Felsberg",
	"Feuchtwangen",
	"Filderstadt",
	"Finsterwalde",
	"Fladungen",
	"Flensburg",
	"Flöha",
	"Flörsheim am Main",
	"Florstadt",
	"Forchheim",
	"Forchtenberg",
	"Forst",
	"Frankenau",
	"Frankenberg",
	"Frankenberg/Sa.",
	"Frankenthal",
	"Frankfurt",
	"Frankfurt am Main",
	"Franzburg",
	"Frauenstein",
	"Frechen",
	"Freiberg",
	"Freiberg am Neckar",
	"Freiburg im Breisgau",
	"Freilassing",
	"Freinsheim",
	"Freising",
	"Freital",
	"Freren",
	"Freudenberg",
	"Freudenstadt",
	"Freyburg",
	"Freystadt",
	"Freyung",
	"Fridingen an der Donau",
	"Friedberg",
	"Friedland",
	"Friedrichroda",
	"Friedrichsdorf",
	"Friedrichshafen",
	"Friedrichstadt",
	"Friedrichsthal",
	"Friesack",
	"Friesoythe",
	"Fritzlar",
	"Frohburg",
	"Fröndenberg",
	"Fulda",
	"Fürstenau",
	"Fürstenberg/Havel",
	"Fürstenfeldbruck",
	"Fürstenwalde",
	"Fürth",
	"Furth im Wald",
	"Furtwangen im Schwarzwald",
	"Füssen",
	"Gadebusch",
	"Gaggenau",
	"Gaildorf",
	"Gammertingen",
	"Garbsen",
	"Garching bei München",
	"Gardelegen",
	"Garding",
	"Gartz",
	"Garz/Rügen",
	"Gau-Algesheim",
	"Gebesee",
	"Gedern",
	"Geesthacht",
	"Geestland",
	"Gefell",
	"Gefrees",
	"Gehrden",
	"Gehren",
	"Geilenkirchen",
	"Geisa",
	"Geiselhöring",
	"Geisenfeld",
	"Geisenheim",
	"Geisingen",
	"Geislingen",
	"Geislingen an der Steige",
	"Geithain",
	"Geldern",
	"Gelnhausen",
	"Gelsenkirchen",
	"Gemünden",
	"Gemünden am Main",
	"Gengenbach",
	"Genthin",
	"Georgsmarienhütte",
	"Gera",
	"Gerabronn",
	"Gerbstedt",
	"Geretsried",
	"Geringswalde",
	"Gerlingen",
	"Germering",
	"Germersheim",
	"Gernsbach",
	"Gernsheim",
	"Gerolstein",
	"Gerolzhofen",
	"Gersfeld",
	"Gersthofen",
	"Gescher",
	"Geseke",
	"Gevelsberg",
	"Geyer",
	"Giengen an der Brenz",
	"Giessen",
	"Gifhorn",
	"Ginsheim-Gustavsburg",
	"Gladbeck",
	"Gladenbach",
	"Glashütte",
	"Glauchau",
	"Glinde",
	"Glücksburg",
	"Glückstadt",
	"Gnoien",
	"Goch",
	"Goldberg",
	"Goldkronach",
	"Golssen",
	"Gommern",
	"Göppingen",
	"Görlitz",
	"Goslar",
	"Gössnitz",
	"Gotha",
	"Göttingen",
	"Grabow",
	"Grafenau",
	"Gräfenberg",
	"Gräfenhainichen",
	"Gräfenthal",
	"Grafenwöhr",
	"Grafing bei München",
	"Gransee",
	"Grebenau",
	"Grebenstein",
	"Greding",
	"Greifswald",
	"Greiz",
	"Greussen",
	"Greven",
	"Grevenbroich",
	"Grevesmühlen",
	"Griesheim",
	"Grimma",
	"Grimmen",
	"Gröditz",
	"Groitzsch",
	"Gronau",
	"Gröningen",
	"Grossalmerode",
	"Gross-Bieberau",
	"Grossbottwar",
	"Grossbreitenbach",
	"Grossenehrich",
	"Grossenhain",
	"Gross-Gerau",
	"Grossräschen",
	"Grossröhrsdorf",
	"Grossschirma",
	"Gross-Umstadt",
	"Grünberg",
	"Grünhain-Beierfeld",
	"Grünsfeld",
	"Grünstadt",
	"Guben",
	"Gudensberg",
	"Güglingen",
	"Gummersbach",
	"Gundelfingen an der Donau",
	"Gundelsheim",
	"Günzburg",
	"Gunzenhausen",
	"Güsten",
	"Güstrow",
	"Gütersloh",
	"Gützkow",
	"Haan",
	"Hachenburg",
	"Hadamar",
	"Hagen",
	"Hagenbach",
	"Hagenow",
	"Haiger",
	"Haigerloch",
	"Hainichen",
	"Haiterbach",
	"Halberstadt",
	"Haldensleben",
	"Halle",
	"Hallenberg",
	"Hallstadt",
	"Haltern am See",
	"Halver",
	"Hamburg",
	"Hameln",
	"Hamm",
	"Hammelburg",
	"Hamminkeln",
	"Hanau",
	"Hann. Münden",
	"Hanover",
	"Harburg",
	"Hardegsen",
	"Haren",
	"Harsewinkel",
	"Hartenstein",
	"Hartha",
	"Harzgerode",
	"Haselünne",
	"Haslach im Kinzigtal",
	"Hassfurt",
	"Hattersheim am Main",
	"Hattingen",
	"Hatzfeld",
	"Hausach",
	"Hauzenberg",
	"Havelberg",
	"Havelsee",
	"Hayingen",
	"Hechingen",
	"Hecklingen",
	"Heide",
	"Heideck",
	"Heidelberg",
	"Heidenau",
	"Heidenheim an der Brenz",
	"Heilbad Heiligenstadt",
	"Heilbronn",
	"Heiligenhafen",
	"Heiligenhaus",
	"Heilsbronn",
	"Heimbach",
	"Heimsheim",
	"Heinsberg",
	"Heitersheim",
	"Heldrungen",
	"Helmbrechts",
	"Helmstedt",
	"Hemau",
	"Hemer",
	"Hemmingen",
	"Hemmoor",
	"Hemsbach",
	"Hennef",
	"Hennigsdorf",
	"Heppenheim",
	"Herbolzheim",
	"Herborn",
	"Herbrechtingen",
	"Herbstein",
	"Herdecke",
	"Herdorf",
	"Herford",
	"Heringen",
	"Heringen/Helme",
	"Hermeskeil",
	"Hermsdorf",
	"Herne",
	"Herrenberg",
	"Herrieden",
	"Herrnhut",
	"Hersbruck",
	"Herten",
	"Herzberg",
	"Herzberg am Harz",
	"Herzogenaurach",
	"Herzogenrath",
	"Hessisch Lichtenau",
	"Hessisch Oldendorf",
	"Hettingen",
	"Hettstedt",
	"Heubach",
	"Heusenstamm",
	"Hilchenbach",
	"Hildburghausen",
	"Hilden",
	"Hildesheim",
	"Hillesheim",
	"Hilpoltstein",
	"Hirschau",
	"Hirschberg",
	"Hirschhorn",
	"Hitzacker",
	"Hochheim am Main",
	"Höchstadt an der Aisch",
	"Höchstädt an der Donau",
	"Hockenheim",
	"Hof",
	"Hofgeismar",
	"Hofheim",
	"Hofheim am Taunus",
	"Hohenberg an der Eger",
	"Hohenleuben",
	"Hohenmölsen",
	"Hohen Neuendorf",
	"Hohenstein-Ernstthal",
	"Hohnstein",
	"Höhr-Grenzhausen",
	"Hollfeld",
	"Holzgerlingen",
	"Holzminden",
	"Homberg",
	"Homburg",
	"Horb am Neckar",
	"Hornbach",
	"Horn-Bad Meinberg",
	"Hornberg",
	"Hörstel",
	"Horstmar",
	"Höxter",
	"Hoya",
	"Hoyerswerda",
	"Hückelhoven",
	"Hückeswagen",
	"Hüfingen",
	"Hünfeld",
	"Hungen",
	"Hürth",
	"Husum",
	"Ibbenbüren",
	"Ichenhausen",
	"Idar-Oberstein",
	"Idstein",
	"Illertissen",
	"Ilmenau",
	"Ilsenburg",
	"Ilshofen",
	"Immenhausen",
	"Immenstadt im Allgäu",
	"Ingelfingen",
	"Ingelheim am Rhein",
	"Ingolstadt",
	"Iphofen",
	"Iserlohn",
	"Isny im Allgäu",
	"Isselburg",
	"Itzehoe",
	"Jarmen",
	"Jena",
	"Jerichow",
	"Jessen",
	"Jever",
	"Joachimsthal",
	"Johanngeorgenstadt",
	"Jöhstadt",
	"Jülich",
	"Jüterbog",
	"Kaarst",
	"Kahla",
	"Kaisersesch",
	"Kaiserslautern",
	"Kalbe",
	"Kalkar",
	"Kaltenkirchen",
	"Kaltennordheim",
	"Kamen",
	"Kamenz",
	"Kamp-Lintfort",
	"Kandel",
	"Kandern",
	"Kappeln",
	"Karben",
	"Karlsruhe",
	"Karlstadt",
	"Kassel",
	"Kastellaun",
	"Katzenelnbogen",
	"Kaub",
	"Kaufbeuren",
	"Kehl",
	"Kelbra",
	"Kelheim",
	"Kelkheim",
	"Kellinghusen",
	"Kelsterbach",
	"Kemberg",
	"Kemnath",
	"Kempen",
	"Kempten im Allgäu",
	"Kenzingen",
	"Kerpen",
	"Ketzin/Havel",
	"Kevelaer",
	"Kiel",
	"Kierspe",
	"Kindelbrück",
	"Kirchberg",
	"Kirchberg an der Jagst",
	"Kirchen",
	"Kirchenlamitz",
	"Kirchhain",
	"Kirchheimbolanden",
	"Kirchheim unter Teck",
	"Kirn",
	"Kirtorf",
	"Kitzingen",
	"Kitzscher",
	"Kleve",
	"Klingenberg am Main",
	"Klingenthal/Sa.",
	"Klötze",
	"Klütz",
	"Knittlingen",
	"Koblenz",
	"Kohren-Sahlis",
	"Kolbermoor",
	"Kölleda",
	"Königsberg in Bayern",
	"Königsbrück",
	"Königsbrunn",
	"Königsee-Rottenbach",
	"Königslutter",
	"Königstein",
	"Königstein im Taunus",
	"Königswinter",
	"Königs Wusterhausen",
	"Könnern",
	"Konstanz",
	"Konz",
	"Korbach",
	"Korntal-Münchingen",
	"Kornwestheim",
	"Korschenbroich",
	"Köthen",
	"Kraichtal",
	"Krakow am See",
	"Kranichfeld",
	"Krautheim",
	"Krefeld",
	"Kremmen",
	"Krempe",
	"Kreuztal",
	"Kronach",
	"Kronberg im Taunus",
	"Kröpelin",
	"Kroppenstedt",
	"Krumbach",
	"Kühlungsborn",
	"Kulmbach",
	"Külsheim",
	"Künzelsau",
	"Kupferberg",
	"Kuppenheim",
	"Kusel",
	"Kyllburg",
	"Kyritz",
	"Laage",
	"Laatzen",
	"Ladenburg",
	"Lage",
	"Lahnstein",
	"Lahr/Schwarzwald",
	"Laichingen",
	"Lambrecht",
	"Lampertheim",
	"Landau an der Isar",
	"Landau in der Pfalz",
	"Landsberg",
	"Landsberg am Lech",
	"Landshut",
	"Landstuhl",
	"Langelsheim",
	"Langen",
	"Langenau",
	"Langenburg",
	"Langenfeld",
	"Langenhagen",
	"Langenselbold",
	"Langenzenn",
	"Langewiesen",
	"Lassan",
	"Laubach",
	"Laucha an der Unstrut",
	"Lauchhammer",
	"Lauchheim",
	"Lauda-Königshofen",
	"Lauenburg",
	"Lauf an der Pegnitz",
	"Laufen",
	"Laufenburg",
	"Lauffen am Neckar",
	"Lauingen",
	"Laupheim",
	"Lauscha",
	"Lauta",
	"Lauterbach",
	"Lauter-Bernsbach",
	"Lauterecken",
	"Lauterstein",
	"Lebach",
	"Lebus",
	"Leer",
	"Lehesten",
	"Lehrte",
	"Leichlingen",
	"Leimen",
	"Leinefelde-Worbis",
	"Leinfelden-Echterdingen",
	"Leipheim",
	"Leipzig",
	"Leisnig",
	"Lemgo",
	"Lengenfeld",
	"Lengerich",
	"Lennestadt",
	"Lenzen",
	"Leonberg",
	"Leun",
	"Leuna",
	"Leutenberg",
	"Leutershausen",
	"Leutkirch im Allgäu",
	"Leverkusen",
	"Lich",
	"Lichtenau",
	"Lichtenberg",
	"Lichtenfels",
	"Lichtenstein/Sa.",
	"Liebenau",
	"Liebenwalde",
	"Lieberose",
	"Liebstadt",
	"Limbach-Oberfrohna",
	"Limburg an der Lahn",
	"Lindau",
	"Linden",
	"Lindenberg im Allgäu",
	"Lindenfels",
	"Lindow",
	"Lingen",
	"Linnich",
	"Linz am Rhein",
	"Lippstadt",
	"Löbau",
	"Löffingen",
	"Lohmar",
	"Lohne",
	"Löhne",
	"Lohr am Main",
	"Loitz",
	"Lollar",
	"Lommatzsch",
	"Löningen",
	"Lorch",
	"Lörrach",
	"Lorsch",
	"Lössnitz",
	"Löwenstein",
	"Lübbecke",
	"Lübben",
	"Lübbenau",
	"Lübeck",
	"Lübtheen",
	"Lübz",
	"Lüchow",
	"Lucka",
	"Luckau",
	"Luckenwalde",
	"Lüdenscheid",
	"Lüdinghausen",
	"Ludwigsburg",
	"Ludwigsfelde",
	"Ludwigshafen am Rhein",
	"Ludwigslust",
	"Ludwigsstadt",
	"Lugau/Erzgeb.",
	"Lügde",
	"Lüneburg",
	"Lünen",
	"Lunzenau",
	"Lütjenburg",
	"Lützen",
	"Lychen",
	"Magdala",
	"Magdeburg",
	"Mahlberg",
	"Mainbernheim",
	"Mainburg",
	"Maintal",
	"Mainz",
	"Malchin",
	"Malchow",
	"Manderscheid",
	"Mannheim",
	"Mansfeld",
	"Marbach am Neckar",
	"Marburg",
	"Marienberg",
	"Marienmünster",
	"Markdorf",
	"Markgröningen",
	"Märkisch Buchholz",
	"Markkleeberg",
	"Markneukirchen",
	"Markranstädt",
	"Marktbreit",
	"Marktheidenfeld",
	"Marktleuthen",
	"Marktoberdorf",
	"Marktredwitz",
	"Marktsteft",
	"Marl",
	"Marlow",
	"Marne",
	"Marsberg",
	"Maulbronn",
	"Maxhütte-Haidhof",
	"Mayen",
	"Mechernich",
	"Meckenheim",
	"Medebach",
	"Meerane",
	"Meerbusch",
	"Meersburg",
	"Meinerzhagen",
	"Meiningen",
	"Meisenheim",
	"Meissen",
	"Meldorf",
	"Melle",
	"Mellrichstadt",
	"Melsungen",
	"Memmingen",
	"Menden",
	"Mendig",
	"Mengen",
	"Meppen",
	"Merkendorf",
	"Merseburg",
	"Merzig",
	"Meschede",
	"Messkirch",
	"Messstetten",
	"Mettmann",
	"Metzingen",
	"Meuselwitz",
	"Meyenburg",
	"Michelstadt",
	"Miesbach",
	"Miltenberg",
	"Mindelheim",
	"Minden",
	"Mirow",
	"Mittenwalde",
	"Mitterteich",
	"Mittweida",
	"Möckern",
	"Möckmühl",
	"Moers",
	"Mölln",
	"Mönchengladbach",
	"Monheim",
	"Monheim am Rhein",
	"Monschau",
	"Montabaur",
	"Moosburg",
	"Mörfelden-Walldorf",
	"Moringen",
	"Mosbach",
	"Mössingen",
	"Mücheln",
	"Mügeln",
	"Mühlacker",
	"Mühlberg",
	"Mühldorf",
	"Mühlhausen",
	"Mühlheim am Main",
	"Mühlheim an der Donau",
	"Mülheim an der Ruhr",
	"Mülheim-Kärlich",
	"Müllheim",
	"Müllrose",
	"Münchberg",
	"Müncheberg",
	"Münchenbernsdorf",
	"Munderkingen",
	"Munich",
	"Münnerstadt",
	"Münsingen",
	"Munster",
	"Münster",
	"Münstermaifeld",
	"Münzenberg",
	"Murrhardt",
	"Mylau",
	"Nabburg",
	"Nagold",
	"Naila",
	"Nassau",
	"Nastätten",
	"Nauen",
	"Naumburg",
	"Naunhof",
	"Nebra",
	"Neckarbischofsheim",
	"Neckargemünd",
	"Neckarsteinach",
	"Neckarsulm",
	"Neresheim",
	"Netphen",
	"Nettetal",
	"Netzschkau",
	"Neu-Anspach",
	"Neubrandenburg",
	"Neubukow",
	"Neubulach",
	"Neuburg an der Donau",
	"Neudenau",
	"Neuenbürg",
	"Neuenburg am Rhein",
	"Neuenhaus",
	"Neuenrade",
	"Neuenstadt am Kocher",
	"Neuenstein",
	"Neuerburg",
	"Neuffen",
	"Neuhaus am Rennweg",
	"Neu-Isenburg",
	"Neukalen",
	"Neukirchen",
	"Neukirchen-Vluyn",
	"Neukloster",
	"Neumark",
	"Neumarkt in der Oberpfalz",
	"Neumarkt-Sankt Veit",
	"Neumünster",
	"Neunburg vorm Wald",
	"Neunkirchen",
	"Neuötting",
	"Neuruppin",
	"Neusalza-Spremberg",
	"Neusäss",
	"Neuss",
	"Neustadt",
	"Neustadt am Kulm",
	"Neustadt am Rübenberge",
	"Neustadt an der Aisch",
	"Neustadt an der Donau",
	"Neustadt an der Orla",
	"Neustadt an der Waldnaab",
	"Neustadt an der Weinstrasse",
	"Neustadt bei Coburg",
	"Neustadt-Glewe",
	"Neustadt in Holstein",
	"Neustadt in Sachsen",
	"Neustrelitz",
	"Neutraubling",
	"Neu-Ulm",
	"Neuwied",
	"Nidda",
	"Niddatal",
	"Nidderau",
	"Nideggen",
	"Niebüll",
	"Niedenstein",
	"Niederkassel",
	"Niedernhall",
	"Nieder-Olm",
	"Niederstetten",
	"Niederstotzingen",
	"Nieheim",
	"Niemegk",
	"Nienburg",
	"Nierstein",
	"Niesky",
	"Nittenau",
	"Norden",
	"Nordenham",
	"Norderney",
	"Norderstedt",
	"Nordhausen",
	"Nordhorn",
	"Nördlingen",
	"Northeim",
	"Nortorf",
	"Nossen",
	"Nuremberg",
	"Nürtingen",
	"Oberasbach",
	"Oberharz am Brocken",
	"Oberhausen",
	"Oberhof",
	"Oberkirch",
	"Oberkochen",
	"Oberlungwitz",
	"Obermoschel",
	"Obernburg am Main",
	"Oberndorf am Neckar",
	"Obernkirchen",
	"Ober-Ramstadt",
	"Oberriexingen",
	"Obertshausen",
	"Oberursel",
	"Oberviechtach",
	"Oberweissbach/Thür. Wald",
	"Oberwesel",
	"Oberwiesenthal",
	"Ochsenfurt",
	"Ochsenhausen",
	"Ochtrup",
	"Oderberg",
	"Oebisfelde-Weferlingen",
	"Oederan",
	"Oelde",
	"Oelsnitz",
	"Oelsnitz/Erzgeb.",
	"Oer-Erkenschwick",
	"Oerlinghausen",
	"Oestrich-Winkel",
	"Oettingen in Bayern",
	"Offenbach am Main",
	"Offenburg",
	"Ohrdruf",
	"Öhringen",
	"Olbernhau",
	"Olching",
	"Oldenburg",
	"Oldenburg in Holstein",
	"Olfen",
	"Olpe",
	"Olsberg",
	"Oppenau",
	"Oppenheim",
	"Oranienbaum-Wörlitz",
	"Oranienburg",
	"Orlamünde",
	"Ornbau",
	"Ortenberg",
	"Ortrand",
	"Oschatz",
	"Oschersleben",
	"Osnabrück",
	"Osterburg",
	"Osterburken",
	"Osterfeld",
	"Osterhofen",
	"Osterholz-Scharmbeck",
	"Osterode am Harz",
	"Osterwieck",
	"Ostfildern",
	"Ostheim vor der Rhön",
	"Osthofen",
	"Östringen",
	"Ostritz",
	"Otterberg",
	"Otterndorf",
	"Ottweiler",
	"Overath",
	"Owen",
	"Paderborn",
	"Papenburg",
	"Pappenheim",
	"Parchim",
	"Parsberg",
	"Pasewalk",
	"Passau",
	"Pattensen",
	"Pausa-Mühltroff",
	"Pegau",
	"Pegnitz",
	"Peine",
	"Peitz",
	"Penig",
	"Penkun",
	"Penzberg",
	"Penzlin",
	"Perleberg",
	"Petershagen",
	"Pfaffenhofen an der Ilm",
	"Pfarrkirchen",
	"Pforzheim",
	"Pfreimd",
	"Pfullendorf",
	"Pfullingen",
	"Pfungstadt",
	"Philippsburg",
	"Pinneberg",
	"Pirmasens",
	"Pirna",
	"Plattling",
	"Plau am See",
	"Plaue",
	"Plauen",
	"Plettenberg",
	"Pleystein",
	"Plochingen",
	"Plön",
	"Pockau-Lengefeld",
	"Pocking",
	"Pohlheim",
	"Polch",
	"Porta Westfalica",
	"Pössneck",
	"Potsdam",
	"Pottenstein",
	"Preetz",
	"Premnitz",
	"Prenzlau",
	"Pressath",
	"Preussisch Oldendorf",
	"Prichsenstadt",
	"Pritzwalk",
	"Prüm",
	"Puchheim",
	"Pulheim",
	"Pulsnitz",
	"Putbus",
	"Putlitz",
	"Püttlingen",
	"Quakenbrück",
	"Quedlinburg",
	"Querfurt",
	"Quickborn",
	"Rabenau",
	"Radeberg",
	"Radebeul",
	"Radeburg",
	"Radevormwald",
	"Radolfzell am Bodensee",
	"Raguhn-Jessnitz",
	"Rahden",
	"Rain",
	"Ramstein-Miesenbach",
	"Ranis",
	"Ransbach-Baumbach",
	"Rastatt",
	"Rastenberg",
	"Rathenow",
	"Ratingen",
	"Ratzeburg",
	"Rauenberg",
	"Raunheim",
	"Rauschenberg",
	"Ravensburg",
	"Ravenstein",
	"Recklinghausen",
	"Rees",
	"Regen",
	"Regensburg",
	"Regis-Breitingen",
	"Rehau",
	"Rehburg-Loccum",
	"Rehna",
	"Reichelsheim",
	"Reichenbach",
	"Reinbek",
	"Reinfeld, Holstein",
	"Reinheim",
	"Remagen",
	"Remda-Teichel",
	"Remscheid",
	"Remseck am Neckar",
	"Renchen",
	"Rendsburg",
	"Rennerod",
	"Renningen",
	"Rerik",
	"Rethem",
	"Reutlingen",
	"Rheda-Wiedenbrück",
	"Rhede",
	"Rheinau",
	"Rheinbach",
	"Rheinberg",
	"Rheinböllen",
	"Rheine",
	"Rheinfelden",
	"Rheinsberg",
	"Rheinstetten",
	"Rhens",
	"Rhinow",
	"Ribnitz-Damgarten",
	"Richtenberg",
	"Riedenburg",
	"Riedlingen",
	"Riedstadt",
	"Rieneck",
	"Riesa",
	"Rietberg",
	"Rinteln",
	"Röbel/Müritz",
	"Rochlitz",
	"Rockenhausen",
	"Rodalben",
	"Rodenberg",
	"Rödental",
	"Rödermark",
	"Rodewisch",
	"Rodgau",
	"Roding",
	"Römhild",
	"Romrod",
	"Ronneburg",
	"Ronnenberg",
	"Rosbach vor der Höhe",
	"Rosenfeld",
	"Rosenheim",
	"Rosenthal",
	"Rösrath",
	"Rossleben",
	"Rosswein",
	"Rostock",
	"Rotenburg an der Fulda",
	"Rotenburg an der Wümme",
	"Roth",
	"Rötha",
	"Röthenbach an der Pegnitz",
	"Rothenburg",
	"Rothenburg ob der Tauber",
	"Rothenfels",
	"Rottenburg a.d.Laaber",
	"Rottenburg am Neckar",
	"Röttingen",
	"Rottweil",
	"Rötz",
	"Rüdesheim",
	"Rudolstadt",
	"Ruhla",
	"Ruhland",
	"Runkel",
	"Rüsselsheim",
	"Rutesheim",
	"Rüthen",
	"Saalburg-Ebersdorf",
	"Saalfeld",
	"Saarbrücken",
	"Saarburg",
	"Saarlouis",
	"Sachsenhagen",
	"Sachsenheim",
	"Salzgitter",
	"Salzkotten",
	"Salzwedel",
	"Sandau",
	"Sandersdorf-Brehna",
	"Sangerhausen",
	"Sankt Augustin",
	"Sankt Goar",
	"Sankt Goarshausen",
	"Sarstedt",
	"Sassenberg",
	"Sassnitz",
	"Sayda",
	"Schalkau",
	"Schauenstein",
	"Scheer",
	"Scheibenberg",
	"Scheinfeld",
	"Schelklingen",
	"Schenefeld",
	"Schesslitz",
	"Schieder-Schwalenberg",
	"Schifferstadt",
	"Schillingsfürst",
	"Schiltach",
	"Schirgiswalde-Kirschau",
	"Schkeuditz",
	"Schkölen",
	"Schleiden",
	"Schleiz",
	"Schleswig",
	"Schlettau",
	"Schleusingen",
	"Schlieben",
	"Schlitz",
	"Schloss Holte-Stukenbrock",
	"Schlotheim",
	"Schlüchtern",
	"Schlüsselfeld",
	"Schmalkalden",
	"Schmallenberg",
	"Schmölln",
	"Schnackenburg",
	"Schnaittenbach",
	"Schneeberg",
	"Schneverdingen",
	"Schömberg",
	"Schönau",
	"Schönau im Schwarzwald",
	"Schönberg",
	"Schönebeck",
	"Schöneck/Vogtl.",
	"Schönewalde",
	"Schongau",
	"Schöningen",
	"Schönsee",
	"Schönwald",
	"Schopfheim",
	"Schöppenstedt",
	"Schorndorf",
	"Schortens",
	"Schotten",
	"Schramberg",
	"Schraplau",
	"Schriesheim",
	"Schrobenhausen",
	"Schrozberg",
	"Schüttorf",
	"Schwaan",
	"Schwabach",
	"Schwäbisch Gmünd",
	"Schwäbisch Hall",
	"Schwabmünchen",
	"Schwaigern",
	"Schwalbach am Taunus",
	"Schwalmstadt",
	"Schwandorf",
	"Schwanebeck",
	"Schwarzenbach am Wald",
	"Schwarzenbach an der Saale",
	"Schwarzenbek",
	"Schwarzenberg/Erzgeb.",
	"Schwarzenborn",
	"Schwarzheide",
	"Schwedt",
	"Schweich",
	"Schweinfurt",
	"Schwelm",
	"Schwentinental",
	"Schwerin",
	"Schwerte",
	"Schwetzingen",
	"Sebnitz",
	"Seehausen",
	"Seeland",
	"Seelow",
	"Seelze",
	"Seesen",
	"Sehnde",
	"Seifhennersdorf",
	"Selb",
	"Selbitz",
	"Seligenstadt",
	"Selm",
	"Selters",
	"Senden",
	"Sendenhorst",
	"Senftenberg",
	"Sesslach",
	"Siegburg",
	"Siegen",
	"Sigmaringen",
	"Simbach am Inn",
	"Simmern",
	"Sindelfingen",
	"Singen",
	"Sinsheim",
	"Sinzig",
	"Soest",
	"Solingen",
	"Solms",
	"Soltau",
	"Sömmerda",
	"Sondershausen",
	"Sonneberg",
	"Sonnewalde",
	"Sonthofen",
	"Sontra",
	"Spaichingen",
	"Spalt",
	"Spangenberg",
	"Speicher",
	"Spenge",
	"Speyer",
	"Spremberg",
	"Springe",
	"Sprockhövel",
	"Stade",
	"Stadtallendorf",
	"Stadtbergen",
	"Stadthagen",
	"Stadtilm",
	"Stadtlengsfeld",
	"Stadtlohn",
	"Stadtoldendorf",
	"Stadtprozelten",
	"Stadtroda",
	"Stadtsteinach",
	"Stadt Wehlen",
	"Starnberg",
	"Stassfurt",
	"Staufenberg",
	"Staufen im Breisgau",
	"Stavenhagen",
	"St. Blasien",
	"Stein",
	"Steinach",
	"Steinau an der Strasse",
	"Steinbach",
	"Steinbach-Hallenberg",
	"Steinfurt",
	"Steinheim",
	"Steinheim an der Murr",
	"Stendal",
	"Sternberg",
	"St. Georgen im Schwarzwald",
	"St. Ingbert",
	"Stockach",
	"Stolberg",
	"Stollberg",
	"Stolpen",
	"Storkow",
	"Stössen",
	"Straelen",
	"Stralsund",
	"Strasburg",
	"Straubing",
	"Strausberg",
	"Strehla",
	"Stromberg",
	"Stühlingen",
	"Stutensee",
	"Stuttgart",
	"St. Wendel",
	"Südliches Anhalt",
	"Suhl",
	"Sulingen",
	"Sulz am Neckar",
	"Sulzbach-Rosenberg",
	"Sulzbach/ Saar",
	"Sulzburg",
	"Sundern",
	"Süssen",
	"Syke",
	"Tambach-Dietharz",
	"Tangerhütte",
	"Tangermünde",
	"Tann",
	"Tanna",
	"Tauberbischofsheim",
	"Taucha",
	"Taunusstein",
	"Tecklenburg",
	"Tegernsee",
	"Telgte",
	"Teltow",
	"Templin",
	"Tengen",
	"Tessin",
	"Teterow",
	"Tettnang",
	"Teublitz",
	"Teuchern",
	"Teupitz",
	"Teuschnitz",
	"Thale",
	"Thalheim/Erzgeb.",
	"Thannhausen",
	"Tharandt",
	"Themar",
	"Thum",
	"Tirschenreuth",
	"Titisee-Neustadt",
	"Tittmoning",
	"Todtnau",
	"Töging am Inn",
	"Tönisvorst",
	"Tönning",
	"Torgau",
	"Torgelow",
	"Tornesch",
	"Traben-Trarbach",
	"Traunreut",
	"Traunstein",
	"Trebbin",
	"Trebsen/Mulde",
	"Treffurt",
	"Trendelburg",
	"Treuchtlingen",
	"Treuen",
	"Treuenbrietzen",
	"Triberg im Schwarzwald",
	"Tribsees",
	"Trier",
	"Triptis",
	"Trochtelfingen",
	"Troisdorf",
	"Trossingen",
	"Trostberg",
	"Tübingen",
	"Tuttlingen",
	"Twistringen",
	"Übach-Palenberg",
	"Überlingen",
	"Uebigau-Wahrenbrück",
	"Ueckermünde",
	"Uelzen",
	"Uetersen",
	"Uffenheim",
	"Uhingen",
	"Ulm",
	"Ulmen",
	"Ulrichstein",
	"Ummerstadt",
	"Unkel",
	"Unna",
	"Unterschleissheim",
	"Usedom",
	"Usingen",
	"Uslar",
	"Vacha",
	"Vaihingen an der Enz",
	"Vallendar",
	"Varel",
	"Vechta",
	"Velbert",
	"Velburg",
	"Velden",
	"Velen",
	"Vellberg",
	"Vellmar",
	"Velten",
	"Verden",
	"Veringenstadt",
	"Verl",
	"Versmold",
	"Vetschau/Spreewald",
	"Viechtach",
	"Viernheim",
	"Viersen",
	"Villingen-Schwenningen",
	"Vilsbiburg",
	"Vilseck",
	"Vilshofen",
	"Visselhövede",
	"Vlotho",
	"Voerde",
	"Vogtsburg im Kaiserstuhl",
	"Vohburg an der Donau",
	"Vohenstrauss",
	"Vöhrenbach",
	"Vöhringen",
	"Volkach",
	"Völklingen",
	"Volkmarsen",
	"Vreden",
	"Wachenheim an der Weinstrasse",
	"Wächtersbach",
	"Wadern",
	"Waghäusel",
	"Wahlstedt",
	"Waiblingen",
	"Waibstadt",
	"Waischenfeld",
	"Waldbröl",
	"Waldeck",
	"Waldenbuch",
	"Waldenburg",
	"Waldershof",
	"Waldheim",
	"Waldkappel",
	"Waldkirch",
	"Waldkirchen",
	"Waldkraiburg",
	"Waldmünchen",
	"Waldsassen",
	"Waldshut-Tiengen",
	"Walldorf",
	"Walldürn",
	"Wallenfels",
	"Walsrode",
	"Waltershausen",
	"Waltrop",
	"Wanfried",
	"Wangen im Allgäu",
	"Wanzleben-Börde",
	"Warburg",
	"Waren",
	"Warendorf",
	"Warin",
	"Warstein",
	"Wassenberg",
	"Wasserburg am Inn",
	"Wassertrüdingen",
	"Wasungen",
	"Wedel",
	"Weener",
	"Wegberg",
	"Wegeleben",
	"Wehr",
	"Weida",
	"Weiden in der Oberpfalz",
	"Weikersheim",
	"Weil am Rhein",
	"Weilburg",
	"Weil der Stadt",
	"Weilheim an der Teck",
	"Weilheim in Oberbayern",
	"Weimar",
	"Weingarten",
	"Weinheim",
	"Weinsberg",
	"Weinstadt",
	"Weismain",
	"Weissenberg",
	"Weissenburg in Bayern",
	"Weissenfels",
	"Weissenhorn",
	"Weissensee",
	"Weissenstadt",
	"Weissenthurm",
	"Weisswasser",
	"Weiterstadt",
	"Welzheim",
	"Welzow",
	"Wemding",
	"Wendlingen am Neckar",
	"Werben",
	"Werdau",
	"Werder",
	"Werdohl",
	"Werl",
	"Wermelskirchen",
	"Wernau",
	"Werne",
	"Werneuchen",
	"Wernigerode",
	"Wertheim",
	"Werther",
	"Wertingen",
	"Wesel",
	"Wesenberg",
	"Wesselburen",
	"Wesseling",
	"Westerburg",
	"Westerstede",
	"Wetter",
	"Wettin-Löbejün",
	"Wetzlar",
	"Widdern",
	"Wiehe",
	"Wiehl",
	"Wiesbaden",
	"Wiesensteig",
	"Wiesloch",
	"Wiesmoor",
	"Wildau",
	"Wildberg",
	"Wildenfels",
	"Wildeshausen",
	"Wilhelmshaven",
	"Wilkau-Hasslau",
	"Willebadessen",
	"Willich",
	"Wilsdruff",
	"Wilster",
	"Wilthen",
	"Windischeschenbach",
	"Windsbach",
	"Winnenden",
	"Winsen",
	"Winterberg",
	"Wipperfürth",
	"Wirges",
	"Wismar",
	"Wissen",
	"Witten",
	"Wittenberg",
	"Wittenberge",
	"Wittenburg",
	"Wittichenau",
	"Wittingen",
	"Wittlich",
	"Wittmund",
	"Wittstock/Dosse",
	"Witzenhausen",
	"Woldegk",
	"Wolfach",
	"Wolfenbüttel",
	"Wolfhagen",
	"Wolframs-Eschenbach",
	"Wolfratshausen",
	"Wolfsburg",
	"Wolfstein",
	"Wolgast",
	"Wolkenstein",
	"Wolmirstedt",
	"Worms",
	"Wörrstadt",
	"Wörth am Main",
	"Wörth am Rhein",
	"Wörth an der Donau",
	"Wriezen",
	"Wülfrath",
	"Wunsiedel",
	"Wunstorf",
	"Wuppertal",
	"Würselen",
	"Wurzbach",
	"Würzburg",
	"Wurzen",
	"Wustrow",
	"Wyk auf Föhr",
	"Xanten",
	"Zahna-Elster",
	"Zarrentin",
	"Zehdenick",
	"Zeil am Main",
	"Zeitz",
	"Zell",
	"Zella-Mehlis",
	"Zell am Harmersbach",
	"Zell im Wiesental",
	"Zerbst",
	"Zeulenroda-Triebes",
	"Zeven",
	"Ziegenrück",
	"Zierenberg",
	"Ziesar",
	"Zirndorf",
	"Zittau",
	"Zörbig",
	"Zossen",
	"Zschopau",
	"Zülpich",
	"Zweibrücken",
	"Zwenkau",
	"Zwickau",
	"Zwiesel",
	"Zwingenberg",
	"Zwönitz",
}
end
