function data()
return {
	"Kerkstraat",
	"Schoolstraat",
	"Molenstraat",
	"Dorpsstraat",
	"Molenweg",
	"Julianastraat",
	"Parallelweg",
	"Nieuwstraat",
	"Wilhelminastraat",
	"Sportlaan",
	"Industrieweg",
	"Beatrixstraat",
	"Kastanjelaan",
	"Stationsweg",
	"Eikenlaan",
	"Markt",
	"Prins Bernhardstraat",
	"Emmastraat",
	"Beukenlaan",
	"Straatweg",
	"Ringbaan",
	"Verbindingsweg",
	"Jacob Catstraat",
	"Vogelweg",
	"Van Ossstraat",
	"Stastokstraat",
	"Klokjeslaan",
	"Biltstraat",
	"Kalverstraat",
	"Spui",
	"Lange Poten",
	"Blaak",
	"Hofplein",
	"Coolsingel",
	"Leidschestraat",
	"Binnenweg",
	"Steenstraat",
	"Zijlweg",
	"Houtstraat",
	"Neude",
	"Vreeburg",
	"Groote Markt",
	"Sportlaan",
	"Heerestraat",
	"Plein",
	"Loosduinse Kade",
}
end
