function data() return {
	"A Odhners gata",
	"Adolf Edelsvärds gata",
	"Altfiolgatan",
	"Amalia Jönssons gata",
	"Amazonvägen",
	"Amerikagatan",
	"Amiralitetsgatan",
	"Andra långgatan",
	"Antenngatan",
	"Augustus Barks gata",
	"Bangatan",
	"Baldersgatan",
	"Backavägen",
	"Bergkristallgatan",
	"Bergslagsgatan",
	"Beryllgatan",
	"Berzeliigatan",
	"Betaniagatan",
	"Brunnsgatan",
	"Brynolfsgatan",
	"Carl Grimbergsgatan",
	"Carlbergsgatan",
	"Ceresgatan",
	"Cederflychts gata",
	"Chalmers tvärgata",
	"Chalmersgatan",
	"Christina Nilssons gata",
	"Corneliusgatan",
	"Dahlströmsgatan",
	"Datavägen",
	"Deltavägen",
	"Drottninggatan",
	"Delsjövägen",
	"Distansgatan",
	"Djurgårdsgatan",
	"Djupedalsgatan",
	"Doktor Saléns gata",
	"Dragspelsgatan",
	"Ebbe Lieberathsgatan",
	"Eddabacken",
	"Egnahemsvägen",
	"Ejdergatan",
	"Eklandagatan",
	"Ekmansgatan",
	"Elektrovägen",
	"Engdahlsgatan",
	"Engelbrektsgatan",
	"Exportgatan",
	"Fagottgatan",
	"Fjärde långgatan",
	"Folkungagatan",
	"Fredsgatan",
	"Fribergsgatan",
	"Friggagatan",
	"Fyrklöversgatan",
	"Fysikgränd",
	"Föreningsgatan",
	"Första långgatan",
	"Gamelstadsvägen",
	"Garverigatan",
	"Geijersgatan",
	"Golvläggaregatan",
	"Gudmundsgatan",
	"Gyllenkroksgatan",
	"Gårdavägen",
	"Gösta Rahms gata",
	"Götabergsgatan",
	"Göteborgsvägen",
	"Haga nygata",
	"Hagtornsgatan",
	"Hantverkaregatan",
	"Hedåsgatan",
	"Hemstigen",
	"Hjulmakaregatan",
	"Holtermansgatan",
	"Hyltevägen",
	"Högströmsgatan",
	"Hörsalavägen",
	"Idas väg",
	"Idrottsgatan",
	"Igelkottstigen",
	"Illergatan",
	"Importgatan",
	"Ingeborgsgatan",
	"Ingenjörsgatan",
	"Intagsgatan",
	"Irisgatan",
	"Isbergsvägen",
	"Jakobsdalsgatan",
	"Jaktgatan",
	"Januarigatan",
	"Jeppestigen",
	"Johan på gårdas gata",
	"Johannebergsgatan",
	"Jungmansgatan",
	"Jättegrytsgatan",
	"Järnvågsgatan",
	"Järntorgsgtan",
	"Karlfeldtsgatan",
	"Kastellgatan",
	"Kapellgatan",
	"Kronhjortsgatan",
	"Kopparslagaregatan",
	"Korsgatan",
	"Korsvägen",
	"Kortvågsgatan",
	"Kungsladugårdsgatan",
	"Kungsportsavenyn",
	"Laboratoriegatan",
	"Landalagatan",
	"Landshövdingegatan",
	"Lantmilsgatan",
	"Legendgatan",
	"Lergodsgatan",
	"Lilla glasmästaregatan",
	"Lilla stampgatan",
	"Linnégatan",
	"Lorensbergsgatan",
	"Magasinsgatan",
	"Mandolingatan",
	"Margretelundsgatan",
	"Medicinaregatan",
	"Mejerigatan",
	"Mellangatan",
	"Milpålegatan",
	"Molinsgatan",
	"Muraregatan",
	"Mässans gata",
	"Nedre fogelbergsgatan",
	"Nedre kvarnbergsgatan",
	"Nordenskiöldsgatan",
	"Nordhemsgatan",
	"Norra allégatan",
	"Norra hamngatan",
	"Neptunusgatan",
	"Nya allén",
	"Näktergalsgatan",
	"Näverlursgatan",
	"Odinsgatan",
	"Officersbacken",
	"Oktangatan",
	"Oktobergatan",
	"Omvägen",
	"Opalgatan",
	"Ormgatan",
	"Orangerigatan",
	"Orrspelsgatan",
	"Oscar Fredriks kyrkogata",
	"Parkgatan",
	"Peninggatan",
	"Penselgatan",
	"Pipblåsaregatan",
	"Plantagegatan",
	"Postgatan",
	"Pustegårdsgatan",
	"Pusterviksgatan",
	"Påskbergsgatan",
	"Pölgatan",
	"Qvidingsgatan",
	"Raketgatan",
	"Rangeltorpsstigen",
	"Raul Wallenbergs gata",
	"Regnbågsgatan",
	"Ringögatan",
	"Rosenlundsgatan",
	"Räntmästaregatan",
	"Rännvägen",
	"Röhssgatan",
	"Rönnbärsstigen",
	"Sankt sigfridsgatan",
	"Signalgatan",
	"Skolgatan",
	"Skånegatan",
	"Slottsskogsgatan",
	"Stampgatan",
	"Stigbergsliden",
	"Stora nygatan",
	"Södra hamngatan",
	"Södra vägen",
	"Teatergatan",
	"Tegnérsgatan",
	"Teknologgatan",
	"Tellusgatan",
	"Terrassgatan",
	"Torggatan",
	"Tredje långgatan",
	"Tunnbindaregatan",
	"Tågmästaregatan",
	"Töpelsgatan",
	"Ubåtsgatan",
	"Uddeholmsgatan",
	"Uggleåsvägen",
	"Ullevigatan",
	"Ullmansgatan",
	"Ungmästaregatan",
	"Uppfinnaregatan",
	"Urmakaregatan",
	"Utlandsgatan",
	"Utvecklingsgatan",
	"Vallhallagatan",
	"Vallgatan",
	"Vasa kyrkogata",
	"Vasagatan",
	"Verkstadsgatan",
	"Viktor Rydbergsgatan",
	"Viktoriagatan",
	"Vintergatan",
	"Västra hamngatan",
	"Vävlagaregatan",
	"Wadmansgatan",
	"Wallenbergsgatan",
	"Welandersgatan",
	"Wendesgatan",
	"Wieselgrensgatan",
	"Wijkandersgatan",
	"Wingårdsgatan",
	"Wirséns väg",
	"Wrangels trappgata",
	"Wrangelsgatan",
	"Yrvädersgatan",
	"Zachrissonsgatan",
	"Zenitgatan",
	"Åbogårdsgatan",
	"Åbäcksgatan",
	"Åkaregatan",
	"Ålandsgatan",
	"Ånäsvägen",
	"Åsgatan",
	"Åsstigen",
	"Åsbacken",
	"Åvägen",
	"Ädelstensgatan",
	"Älvsborgsgatan",
	"Äppelgatan",
	"Ättehögsgatan",
	"Ättestigen",
	"Öckerögatan",
	"Ödmansgatan",
	"Ögonmåttsgatan",
	"Ögärdesvägen",
	"Önskevädersgatan",
	"Örngatan",
	"Örgrytevägen",
	"Östra hamngatan",
	"Östra larmgatan",
	"Östra skansgatan",
	"Överåsgatan"
} end
