function data()
return {
	"Via Arditi",
	"Via Alleno",
	"Via Alto",
	"Via Basso",
	"Via Barricata",
	"Via Cuppini",
	"Via Cappadocia",
	"Via Dante",
	"Via Dattero",
	"Via Estrena",
	"Via Eclissi",
	"Via Federico VI",
	"Via Marugi",
	"Via Malone",
	"Via Nazionale",
	"Via Nisetti",
	"Via Orso",
	"Via Ottavi",
	"Via Pacine",
	"Via Puccini",
	"Via Porta Nuova",
	"Via Porta Vecchia",
	"Via Rossini",
	"Via Soldati",
	"Via Solfeggio",
	"Via Torquato",
	"Via Taddi",
	"Via Unno",
	"Via Verdi",
	"Via Zuzzulo",
	"Via Zappala",
	"Via Diaz",
	"Via Cadorna",
	"Via Salandra",
	"Via Capello",
	"Via Guillet",
	"Via San Carlo",
	"Via Piave",
	"Via Isonzo",
	"Via Marna",
}
end
