function data()
return {
	"Ahornweg",
	"Am Bahnhof",
	"Amselweg",
	"Am Sportplatz",
	"Bachstrasse",
	"Bahnhofstrasse",
	"Beethovenstrasse",
	"Bergstrasse",
	"Berliner Strasse",
	"Birkenstrasse",
	"Birkenweg",
	"Blumenstrasse",
	"Breslauer Strasse",
	"Brunnenstrasse",
	"Buchenweg",
	"Burgstrasse",
	"Danziger Strasse",
	"Dorfstrasse",
	"Drosselweg",
	"Erlenweg",
	"Fasanenweg",
	"Feldstrasse",
	"Finkenweg",
	"Fliederweg",
	"Friedhofstrasse",
	"Gartenstrasse",
	"Gartenweg",
	"Göthestrasse",
	"Grüner Weg",
	"Hauptstrasse",
	"Heideweg",
	"Im Winkel",
	"Industriestrasse",
	"Jahnstrasse",
	"Kapellenweg",
	"Kastanienweg",
	"Kiefernweg",
	"Kirchgasse",
	"Kirchplatz",
	"Kirchstrasse",
	"Kirchweg",
	"Königsberger Strasse",
	"Lerchenweg",
	"Lessingstrasse",
	"Lindenstrasse",
	"Lindenweg",
	"Marktplatz",
	"Meisenweg",
	"Mittelstrasse",
	"Mittelweg",
	"Mozartstrasse",
	"Mühlenstrasse",
	"Mühlenweg",
	"Mühlweg",
	"Neue Strasse",
	"Parkstrasse",
	"Poststrasse",
	"Raiffeisenstrasse",
	"Ringstrasse",
	"Römerstrasse",
	"Rosenstrasse",
	"Rosenweg",
	"Schillerstrasse",
	"Schlossstrasse",
	"Schulstrasse",
	"Schulweg",
	"Schützenstrasse",
	"Talstrasse",
	"Tannenweg",
	"Tulpenweg",
	"Uhlandstrasse",
	"Waldstrasse",
	"Waldweg",
	"Wichenweg",
	"Wiesenstrasse",
	"Wiesenweg",
}
end
