function data()
return {
	"Albert Road",
	"Alexander Road",
	"Broadway",
	"Chester Road",
	"Church Lane",
	"Church Road",
	"Church Street",
	"George Street",
	"Grange Road",
	"Green Lane",
	"Grove Road",
	"Highfield Road",
	"High Street",
	"Kings Road",
	"King Street",
	"Kingsway",
	"London Road",
	"Main Road",
	"Main Street",
	"Manchester Road",
	"Manor Road",
	"Mill Lane",
	"Mill Road",
	"New Road",
	"New Street",
	"North Road",
	"North Street",
	"Park Avenue",
	"Park Lane",
	"Park Road",
	"Queens Road",
	"Queen Street",
	"Queensway",
	"Richmond Road",
	"School Lane",
	"South Street",
	"Springfield Road",
	"Stanley Road",
	"St. John’s Road",
	"The Avenue",
	"The Crescent",
	"The Drive",
	"The Green",
	"The Grove",
	"Victoria Road",
	"Victoria Street",
	"West Street",
	"Windsor Road",
	"York Road",
}
end
