function data()
return {
	"Kongens Gate",
	"Dronningens Gate",
	"Prinsens Gate",
	"Lerkeveien",
	"Buveien",
	"Rosenkrans Gate",
	"Karl Johans Gate",
	"Haakon VII Gate",
	"Drammensveien",
	"Trondheimsveien",
	"Gamle Kongevei",
	"Martin Stokkens Vei",
	"Brattørgata",
	"Bogstad Allè",
	"Bogstadveien",
	"Klostergata",
	"Olav Tryggvasons Gate",
	"Osloveien",
	"Elgvegen",
	"Nedre Eikervei",
	"Professor Smitts Gate",
	"Gjetergata",
	"Elgsetergata",
	"Nedre Slottsgate",
	"Øvre Slottsgate",
	"Operagata",
	"Bygdøy Allè",
	"Ibsens Gate",
	"Holbergs Gate",
	"Storgata",
	"Asbjørnsens Gatae",
	"Kong Carls Gate",
	"Rosenkrantz Gate",
	"Haakon Jarls Gate",
	"Madlaveien",
	"Christies Gate",
	"Magnus Barfots Gate",
	"Teatergaten",
	"Småskansen",
	"Allmenningen",
	"Strandgata",
	"Barnehaugveien",
	"Birger Hatlebakks Veg",
	"Fannestrandvegen",
	"Myrveien",
	"Storrotvegen",
	"Postmyrvegen",
	"Vollabrekka",
	"Ranheimsvegen",
	"Svalevegen",
	"Meisevegen",
	"Starevegen",
	"Lauvsangvegen",
	"Bøckmanns veg",
	"Finn Bergs veg",
	"Stabells veg",
	"Skjermvegen",
	"Hoemshøgda",
	"Linerlevegen",
	"Oskar Braatens veg",
	"Høgsetgrenda",
	"Alheimsvingen",
	"Byåsveien",
	"Granliveien",
	"Vassliveien",
	"Buveien",
	"Mjukliveien",
	"Porsveien",
	"Kjerkveien",
	"Terminalveien",
	"Åsveien",
	"Harestien",
	"Hareveien",
	"Tyriveien",
	"Stasjonsveien",
	"Kosbergveien",
	"Skogliveien",
	"Heggvegen",
	"Ospvegen",
	"Rognvegen",
	"Høgmovegen",
	"Mellomvegen",
	"Ekornvegen",
	"Einervegen",
	"Seljevegen",
	"Konglevegen",
	"Ferjevegen",
	"Auragata",
	"Nedgaardsgata",
	"Ringvegen",
	"Parkvegen",
	"Skippergata",
	"Øygata",
	"Sandbrekkgata",
	"Calmeyers gate",
	"Torggata",
	"Badstugata",
	"Youngs gate",
	"Pløens gate",
	"Møllergata",
	"Hausmanns gate",
	"Heimdalsgata",
	"Akersgata",
	"Grensen",
	"Stortingsgata",
	"Kirkegata",
	"Rådhusgata",
	"Øvre Vollgate",
	"Nedre Vollgate",
	"Tordenskiolds gate",
}
end
